# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl: /
url: //blog.mapleqin.org
date_format: "ordinal"
title: "MapleQin"
subtitle: "Android Engieener"
description: "A Android developer, expert in Android who lives in Beijing."
keywords: MapleQin, Android
favicon: /favicon.ico
timezone: Asia/Shanghai
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: MapleQin
organization: Maple
organization_url: //www.mapleqin.org
github_username: mapleqin
location: Beijing, China
email: qinmaples@gmail.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

  -
    href: /wiki/
    label: 维基

  -
    href: /links/
    label: 链接

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: mapleqin/blog

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment
comments_provider: gitment
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
disqus:
    username: mapleqin
# https://imsun.net/posts/gitment-introduction/
gitment:
    owner: mapleqin
    repo: blog-comments
    oauth:
        client_id: 7365828cebc82d169e23
        client_secret: 51767324c5c5cb0dfe82c0d043fe3b22df8ca601
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : true

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: UA-106770497-1
